version: '2'
services:
  grafana:
    ports:
      - "3001:3001"
    volumes:
      - /var/lib/grafana
    links:
      - influx
    image: grafana/grafana
  influx:
    ports:
      - "8086:8086"
    image: influxdb/influxdb
  jenkins:
    ports:
      - "8100:8100"
    image: jenkins/jenkins